27134 search input fix
instante/web pull request #1
Opened 2016-12-05 15:47 UTC by amcatko

2016-12-06 12:52 UTC, richard-ejem commented on frontend/src/less/components/searchbox.less
> +    @media screen and (max-width: 800px) {
would be better to use bootstrap grid variables (@screen-xs/sm/...-min/max)

2016-12-06 12:52 UTC, richard-ejem commented on frontend/src/less/components/searchbox.less
> +    width: 563px;
maybe extract to less variable?

2016-12-06 12:52 UTC, richard-ejem commented on frontend/src/less/homepage/default.less
> +        display: inline-block;
shouldn't this be a block?

2016-12-06 12:52 UTC, richard-ejem commented on frontend/src/less/components/searchbox.less
> +    >span {
please use a class instead of span, also merge with the definition above (span and >span) as they look to be connected to the same span

2016-12-06 12:52 UTC, richard-ejem commented on frontend/src/less/components/searchbox.less
> +        @media screen and (max-width: 800px) {
please use a variable (ideally bootstrap grid threshold @screen-xx-xx)

2016-12-06 13:41 UTC, amcatko commented on frontend/src/less/components/searchbox.less
> +    width: 563px;
fixed

2016-12-06 13:47 UTC, amcatko commented on frontend/src/less/components/searchbox.less
> +    @media screen and (max-width: 800px) {
fixed

2016-12-06 13:47 UTC, amcatko commented on frontend/src/less/components/searchbox.less
> +        @media screen and (max-width: 800px) {
fixed

2016-12-06 13:53 UTC, amcatko commented on frontend/src/less/homepage/default.less
> +        display: inline-block;
fixed

2016-12-06 13:57 UTC, amcatko commented on frontend/src/less/components/searchbox.less
> +    >span {
fixed

2016-12-08 12:06 UTC, richard-ejem requested changes

2016-12-08 12:06 UTC, richard-ejem commented on frontend/src/less/components/searchbox.less
> +        @media (max-width: @screen-sm-min) {
@amcatko should have been @screen-xs-max :) (using max-width, you probably want xx-xx-max and vice versa)

2016-12-08 12:06 UTC, richard-ejem commented on frontend/src/less/components/searchbox.less
>          padding-right: 20px;
@amcatko please move this to ".how"

2016-12-08 12:06 UTC, richard-ejem commented on frontend/src/less/variables.less
> +@width-searchbox: 563px;
@amcatko please add newline to the end of file, and ideally configure your editor to do it automatically

2016-12-08 12:06 UTC, richard-ejem commented on frontend/src/less/components/searchbox.less
> +    width: @width-searchbox;
@amcatko maybe more general name? :) as the width corresponds also to search input width and would correspond to future elements similarly placed to the center

2016-12-14 12:41 UTC, amcatko commented on frontend/src/less/components/searchbox.less
> +    width: @width-searchbox;
@richard-ejem fixed

2016-12-14 12:42 UTC, amcatko commented on frontend/src/less/components/searchbox.less
>          padding-right: 20px;
@richard-ejem moved

2016-12-14 12:50 UTC, amcatko commented on frontend/src/less/variables.less
> +@width-searchbox: 563px;
solved

2016-12-14 12:50 UTC, amcatko commented on frontend/src/less/components/searchbox.less
> +        @media (max-width: @screen-sm-min) {
fixed

2016-12-15 15:31 UTC, richard-ejem requested changes

2016-12-15 15:31 UTC, richard-ejem commented on frontend/src/less/components/searchbox.less
>          padding-right: 20px;
@amcatko nooo :) just the styles, there is no span.how span, there is just the span.how :)

2017-01-05 09:48 UTC, richard-ejem requested changes

2017-01-05 09:48 UTC, richard-ejem commented on frontend/src/less/components/searchbox.less
> +        line-height: normal;
@amcatko this seems a bit duplicate...

2017-01-27 14:05 UTC, merged