28483 autocomplete
instante/web pull request #2
Opened 2016-12-06 10:24 UTC by amcatko

2016-12-08 12:21 UTC, richard-ejem requested changes

2016-12-08 12:21 UTC, richard-ejem commented on app/Presenters/templates/Homepage/templateHowDoI.latte
> +                                <a href="#">
@amcatko please don't do this as a link, only the upvote icon should be a link (so, add to some hover action and link only to the upvote icon)

2016-12-08 12:21 UTC, richard-ejem commented on app/Presenters/templates/Homepage/templateHowDoI.latte
> +                    <div><a href="#"  class="more">... Request documentation >></a></div>
@amcatko 
* please remove double space before "class"
* replace >> with &gt;&gt; (or add some nicer glyphicon or fa-icon :) )

2016-12-08 12:21 UTC, richard-ejem commented on frontend/src/less/components/autocomplete.less
> +}
@amcatko please add newline to the end of file

2016-12-08 12:21 UTC, richard-ejem commented on frontend/src/less/components/autocomplete.less
> +input.first:focus + .autocomplete.first,
@amcatko input.first is both too generic and too specific :)

- class "first", "second" etc is unnecessary - the + operator will do the work
- rather give some class to the input saying it has autocomplete, like input.with-autocomplete + .autocomplete

2016-12-08 12:21 UTC, richard-ejem commented on frontend/src/less/components/searchbox.less
> +    @media screen and (max-width: 800px) {
@amcatko please use bootstrap grid thresholds (@screen-??-max)

2016-12-08 12:21 UTC, richard-ejem commented on frontend/src/less/components/searchbox.less
> +    @media screen and (max-width: 600px) {
@amcatko please use bootstrap grid thresholds (@screen-??-max)

2016-12-08 12:21 UTC, richard-ejem commented on frontend/src/less/components/searchbox.less
> +        @media screen and (max-width: 800px) {
@amcatko please use bootstrap grid thresholds (@screen-??-max)

2017-01-03 13:18 UTC, amcatko commented on app/Presenters/templates/Homepage/templateHowDoI.latte
> +                    <div><a href="#"  class="more">... Request documentation >></a></div>
Fixed

2017-01-03 13:26 UTC, amcatko commented on app/Presenters/templates/Homepage/templateHowDoI.latte
> +                                <a href="#">
Fixed

2017-01-04 08:21 UTC, amcatko commented on frontend/src/less/components/autocomplete.less
> +input.first:focus + .autocomplete.first,
fixed

2017-01-04 09:19 UTC, amcatko commented on frontend/src/less/components/searchbox.less
> +    @media screen and (max-width: 800px) {
fixed

2017-01-04 09:19 UTC, amcatko commented on frontend/src/less/components/autocomplete.less
> +}
fixed

2017-01-04 09:19 UTC, amcatko commented on frontend/src/less/components/searchbox.less
> +    @media screen and (max-width: 600px) {
fixed

2017-01-04 09:19 UTC, amcatko commented on frontend/src/less/components/searchbox.less
> +        @media screen and (max-width: 800px) {
fixed

2017-03-14 09:03 UTC, richard-ejem requested changes

2017-03-14 09:03 UTC, richard-ejem commented on app/Presenters/templates/Homepage/templateHowDoI.latte
> +            <div id="searchbox">
There shouldn't be multiple elements of the same ID in a document, please use only CSS classes for styling.

2017-03-14 09:03 UTC, richard-ejem commented on app/Presenters/templates/Homepage/templateHowDoI.latte
> +                                <a href="#">
The link is still present here :( just the upvote icon should be a link.

2017-03-14 09:03 UTC, richard-ejem commented on app/Presenters/templates/Homepage/templateHowDoI.latte
> +                <input type="text" name="search_how" placeholder="Create" class="with-autocomplete">
Something went wrong with the magnifier icon: 
<img width="614" alt="snimek obrazovky 2017-03-14 v 10 00 01" src="https://cloud.githubusercontent.com/assets/7109726/23893011/26fb4fbe-089d-11e7-81c4-9c8c1ff1a2d6.png">

2017-04-04 10:37 UTC, merged